### ISSUE TITLE
Consider creating a Hydra searchpath plugin

### ISSUE THREAD

**Issue by omry** [alshedivat/meta-blocks#1]
Check out the [Hydra source plugin example](https://github.com/facebookresearch/hydra/tree/master/plugins/examples/example_searchpath_plugin) (Hydra 1.0) or the [colorlog plugin](https://github.com/facebookresearch/hydra/tree/0.11_branch/plugins/hydra_colorlog) (closest example for 0.11).

Feel free to join the [chat](https://hydra-framework.zulipchat.com/).

**Comment by alshedivat** [comment]
Thanks for the suggestion, the `colorlog` plugin definitely makes the output look neater. As for the search path plugin, for now we'll stick with the functionality available in the latest hydra release as it's easier from maintainability standpoint. Definitely looking forward to upgrading to `hydra-1.0` as soon as it is out!

**Comment by omry** [comment]
Searchpath plugins are available in the current stable release, but there is no good example (The are some small API changes that makes the example in master not great for 0.11.3).
The colorlog plugin is essentially a searchpath plugin, which is why I told you to look at it as an example.

**Comment by alshedivat** [comment]
Oh, now I see. So, adding `MetaBlocksSearchPathPlugin`, say, to `hydra_plugins/meta_blocks_search_path`, and making sure `setup.py` installs it would add `meta_blocks/configs` path to hydra's default search path? But what benefit exactly would that give?

**Comment by omry** [comment]
That is correct.
The idea is that now users can create their own `@hydra.main()`, just like like the one [you have](https://github.com/alshedivat/meta-blocks/blob/617b87b72776f358442adc9315cbf9654969a252/meta_blocks/run.py#L14) but will be able to fully customize it, while still composing from your configs.
They will also be able to compose configs from other Hydra powered frameworks at the same time.

Two additional points of feedback:
1. In your run.py, you really want to use strict mode.
you can disable it in places where you want to manipulate the config, see the [struct mode](https://omegaconf.readthedocs.io/en/1.4_branch/usage.html#struct-flag) in the OmegaConf docs.

2. I saw you mention Jupyter notebook in your readme.
Check the compose API which enables you to compose a configuration object inside a Jupyter notebook.
https://hydra.cc/docs/advanced/compose_api
